//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/PlayerInput/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace InputSystem
{
    /// <summary>
    /// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/PlayerInput/PlayerInputActions.inputactions".
    /// </summary>
    /// <remarks>
    /// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
    /// </remarks>
    /// <example>
    /// <code>
    /// using namespace UnityEngine;
    /// using UnityEngine.InputSystem;
    ///
    /// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
    /// public class Example : MonoBehaviour, MyActions.IPlayerActions
    /// {
    ///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
    ///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
    ///
    ///     void Awake()
    ///     {
    ///         m_Actions = new MyActions_Actions();              // Create asset object.
    ///         m_Player = m_Actions.Player;                      // Extract action map object.
    ///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
    ///     }
    ///
    ///     void OnDestroy()
    ///     {
    ///         m_Actions.Dispose();                              // Destroy asset object.
    ///     }
    ///
    ///     void OnEnable()
    ///     {
    ///         m_Player.Enable();                                // Enable all actions within map.
    ///     }
    ///
    ///     void OnDisable()
    ///     {
    ///         m_Player.Disable();                               // Disable all actions within map.
    ///     }
    ///
    ///     #region Interface implementation of MyActions.IPlayerActions
    ///
    ///     // Invoked when "Move" action is either started, performed or canceled.
    ///     public void OnMove(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
    ///     }
    ///
    ///     // Invoked when "Attack" action is either started, performed or canceled.
    ///     public void OnAttack(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
    ///     }
    ///
    ///     #endregion
    /// }
    /// </code>
    /// </example>
    public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @PlayerInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Win10"",
            ""id"": ""bbdf934f-cb46-49bb-8823-fa4276d8d3cb"",
            ""actions"": [
                {
                    ""name"": ""Move_Player"",
                    ""type"": ""Value"",
                    ""id"": ""21df0a26-24c7-4a33-b626-39cc18a453c5"",
                    ""expectedControlType"": ""Integer"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack_Player"",
                    ""type"": ""Button"",
                    ""id"": ""9c5afda1-8ba4-4fe2-a228-4f2c11e46b46"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchHotBar_Player"",
                    ""type"": ""Value"",
                    ""id"": ""69d1b644-cfab-421b-ad2b-430736048577"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""F"",
                    ""type"": ""Button"",
                    ""id"": ""777359c2-5997-4d67-817d-8f611bc1b191"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""B"",
                    ""type"": ""Button"",
                    ""id"": ""274f59c7-f255-4d54-a227-8f08751fcc8c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CtrlMouse"",
                    ""type"": ""Value"",
                    ""id"": ""497754f7-5360-4392-90aa-0ae21b37ee2c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ESC"",
                    ""type"": ""Button"",
                    ""id"": ""fb4adb07-c276-43ec-9615-45ae52fbb83c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shift"",
                    ""type"": ""Button"",
                    ""id"": ""57cbc055-6ce9-4835-9a3a-c86f43e3fa4c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ctrl"",
                    ""type"": ""Button"",
                    ""id"": ""f97acfb8-7977-4572-ab52-cb9cb249db0b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseScroll"",
                    ""type"": ""Value"",
                    ""id"": ""f6e319e7-656a-4fa8-bf35-d34411cbf865"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Mouse"",
                    ""type"": ""Value"",
                    ""id"": ""2753ebcc-abc6-4b94-a418-536e5133b3fb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""E"",
                    ""type"": ""Button"",
                    ""id"": ""3a3d9a7c-08a7-4819-a436-fca3cd0bcf49"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""Button"",
                    ""id"": ""f6fc3b86-94ce-4a42-8a03-5e4860c0f435"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftClick"",
                    ""type"": ""Button"",
                    ""id"": ""24b45adc-7f5a-475c-816c-4333fc5b6035"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenEquipmentPack"",
                    ""type"": ""Button"",
                    ""id"": ""b4d32ccf-4552-493a-8e96-3623c6e4df3d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenWorkBench"",
                    ""type"": ""Button"",
                    ""id"": ""e4844ab9-da53-41bf-b8e7-d1e643211272"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tab"",
                    ""type"": ""Button"",
                    ""id"": ""68cd0693-34a0-460f-885d-8a51b06161a7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f7c0d424-cb0e-4850-8e25-e0f13654d2da"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move_Player"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9f7eb736-5620-4e14-b451-9b59df0b18cf"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move_Player"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2ffb0ce5-acf9-46ce-8fdb-37483b2ebd7d"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move_Player"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0b2de46d-da2d-4d83-a488-efeaf403de9a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move_Player"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b6109f88-61cd-4baf-93a0-371795eea48e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move_Player"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""991e0d5c-ed20-4fa6-8fa4-bce57fe23fdb"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack_Player"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""672c0f55-df82-4491-b17e-398fa012cd06"",
                    ""path"": ""<Keyboard>/#(1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchHotBar_Player"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f7fb7c6-c924-4b34-a5c5-81120b4870fe"",
                    ""path"": ""<Keyboard>/#(2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchHotBar_Player"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e97cc4d2-c443-4221-8e64-43ba0d821cf2"",
                    ""path"": ""<Keyboard>/#(3)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchHotBar_Player"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2157533a-2721-4357-b528-ea5994e06e20"",
                    ""path"": ""<Keyboard>/#(4)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchHotBar_Player"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de2a149c-e63f-45f9-ade3-8f5ffc685efe"",
                    ""path"": ""<Keyboard>/#(5)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchHotBar_Player"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04fee209-a9ae-4c53-b79c-381c81d46843"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchHotBar_Player"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5b42745-342e-44a8-811e-986ecf8b226d"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchHotBar_Player"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01913989-0f64-4bb8-819e-6e871d088cb0"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchHotBar_Player"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6dbbcf5-fa3f-41f7-b381-dd4da61ccf6e"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchHotBar_Player"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30610b77-3929-4daf-9a28-57d62cad4f01"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""740a4f78-51fb-482a-b7e6-6c084a50b944"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ESC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0b2af0d-03d2-4290-8b79-af6093a96924"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4ba1c8a-c512-4056-80b5-6744e7992365"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""941309b8-4bcc-4bf2-9ecc-43ccfc955760"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ctrl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""0d8e30da-e308-4041-bfcf-d4de3c630db4"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CtrlMouse"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""ed81fa62-c207-4bed-a313-d92c8837db99"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CtrlMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Binding"",
                    ""id"": ""caa8318c-f8ba-486b-8568-1c6409b41385"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CtrlMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6fb0fe49-d5d1-4572-a337-c39c7ce51c2b"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85863121-8f67-42db-b458-cef65c6cf2d3"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d34c481-8501-4aca-abe0-2b2618af12ab"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""E"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a3a7046-84f3-4afe-a4a8-bf4715f48b42"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8a08ff0-e51e-495e-84ac-ba57fc1dd8c1"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f478a89e-afef-42be-991a-c7c47570fce6"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenEquipmentPack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""798800d1-0986-4e44-875a-3812031eda6b"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenWorkBench"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7bbbd030-a567-491a-beb2-f01cc6043b1b"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Win10
            m_Win10 = asset.FindActionMap("Win10", throwIfNotFound: true);
            m_Win10_Move_Player = m_Win10.FindAction("Move_Player", throwIfNotFound: true);
            m_Win10_Attack_Player = m_Win10.FindAction("Attack_Player", throwIfNotFound: true);
            m_Win10_SwitchHotBar_Player = m_Win10.FindAction("SwitchHotBar_Player", throwIfNotFound: true);
            m_Win10_F = m_Win10.FindAction("F", throwIfNotFound: true);
            m_Win10_B = m_Win10.FindAction("B", throwIfNotFound: true);
            m_Win10_CtrlMouse = m_Win10.FindAction("CtrlMouse", throwIfNotFound: true);
            m_Win10_ESC = m_Win10.FindAction("ESC", throwIfNotFound: true);
            m_Win10_Shift = m_Win10.FindAction("Shift", throwIfNotFound: true);
            m_Win10_Ctrl = m_Win10.FindAction("Ctrl", throwIfNotFound: true);
            m_Win10_MouseScroll = m_Win10.FindAction("MouseScroll", throwIfNotFound: true);
            m_Win10_Mouse = m_Win10.FindAction("Mouse", throwIfNotFound: true);
            m_Win10_E = m_Win10.FindAction("E", throwIfNotFound: true);
            m_Win10_RightClick = m_Win10.FindAction("RightClick", throwIfNotFound: true);
            m_Win10_LeftClick = m_Win10.FindAction("LeftClick", throwIfNotFound: true);
            m_Win10_OpenEquipmentPack = m_Win10.FindAction("OpenEquipmentPack", throwIfNotFound: true);
            m_Win10_OpenWorkBench = m_Win10.FindAction("OpenWorkBench", throwIfNotFound: true);
            m_Win10_Tab = m_Win10.FindAction("Tab", throwIfNotFound: true);
        }

        ~@PlayerInputActions()
        {
            UnityEngine.Debug.Assert(!m_Win10.enabled, "This will cause a leak and performance issues, PlayerInputActions.Win10.Disable() has not been called.");
        }

        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Win10
        private readonly InputActionMap m_Win10;
        private List<IWin10Actions> m_Win10ActionsCallbackInterfaces = new List<IWin10Actions>();
        private readonly InputAction m_Win10_Move_Player;
        private readonly InputAction m_Win10_Attack_Player;
        private readonly InputAction m_Win10_SwitchHotBar_Player;
        private readonly InputAction m_Win10_F;
        private readonly InputAction m_Win10_B;
        private readonly InputAction m_Win10_CtrlMouse;
        private readonly InputAction m_Win10_ESC;
        private readonly InputAction m_Win10_Shift;
        private readonly InputAction m_Win10_Ctrl;
        private readonly InputAction m_Win10_MouseScroll;
        private readonly InputAction m_Win10_Mouse;
        private readonly InputAction m_Win10_E;
        private readonly InputAction m_Win10_RightClick;
        private readonly InputAction m_Win10_LeftClick;
        private readonly InputAction m_Win10_OpenEquipmentPack;
        private readonly InputAction m_Win10_OpenWorkBench;
        private readonly InputAction m_Win10_Tab;
        /// <summary>
        /// Provides access to input actions defined in input action map "Win10".
        /// </summary>
        public struct Win10Actions
        {
            private @PlayerInputActions m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public Win10Actions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Win10/Move_Player".
            /// </summary>
            public InputAction @Move_Player => m_Wrapper.m_Win10_Move_Player;
            /// <summary>
            /// Provides access to the underlying input action "Win10/Attack_Player".
            /// </summary>
            public InputAction @Attack_Player => m_Wrapper.m_Win10_Attack_Player;
            /// <summary>
            /// Provides access to the underlying input action "Win10/SwitchHotBar_Player".
            /// </summary>
            public InputAction @SwitchHotBar_Player => m_Wrapper.m_Win10_SwitchHotBar_Player;
            /// <summary>
            /// Provides access to the underlying input action "Win10/F".
            /// </summary>
            public InputAction @F => m_Wrapper.m_Win10_F;
            /// <summary>
            /// Provides access to the underlying input action "Win10/B".
            /// </summary>
            public InputAction @B => m_Wrapper.m_Win10_B;
            /// <summary>
            /// Provides access to the underlying input action "Win10/CtrlMouse".
            /// </summary>
            public InputAction @CtrlMouse => m_Wrapper.m_Win10_CtrlMouse;
            /// <summary>
            /// Provides access to the underlying input action "Win10/ESC".
            /// </summary>
            public InputAction @ESC => m_Wrapper.m_Win10_ESC;
            /// <summary>
            /// Provides access to the underlying input action "Win10/Shift".
            /// </summary>
            public InputAction @Shift => m_Wrapper.m_Win10_Shift;
            /// <summary>
            /// Provides access to the underlying input action "Win10/Ctrl".
            /// </summary>
            public InputAction @Ctrl => m_Wrapper.m_Win10_Ctrl;
            /// <summary>
            /// Provides access to the underlying input action "Win10/MouseScroll".
            /// </summary>
            public InputAction @MouseScroll => m_Wrapper.m_Win10_MouseScroll;
            /// <summary>
            /// Provides access to the underlying input action "Win10/Mouse".
            /// </summary>
            public InputAction @Mouse => m_Wrapper.m_Win10_Mouse;
            /// <summary>
            /// Provides access to the underlying input action "Win10/E".
            /// </summary>
            public InputAction @E => m_Wrapper.m_Win10_E;
            /// <summary>
            /// Provides access to the underlying input action "Win10/RightClick".
            /// </summary>
            public InputAction @RightClick => m_Wrapper.m_Win10_RightClick;
            /// <summary>
            /// Provides access to the underlying input action "Win10/LeftClick".
            /// </summary>
            public InputAction @LeftClick => m_Wrapper.m_Win10_LeftClick;
            /// <summary>
            /// Provides access to the underlying input action "Win10/OpenEquipmentPack".
            /// </summary>
            public InputAction @OpenEquipmentPack => m_Wrapper.m_Win10_OpenEquipmentPack;
            /// <summary>
            /// Provides access to the underlying input action "Win10/OpenWorkBench".
            /// </summary>
            public InputAction @OpenWorkBench => m_Wrapper.m_Win10_OpenWorkBench;
            /// <summary>
            /// Provides access to the underlying input action "Win10/Tab".
            /// </summary>
            public InputAction @Tab => m_Wrapper.m_Win10_Tab;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Win10; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="Win10Actions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(Win10Actions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="Win10Actions" />
            public void AddCallbacks(IWin10Actions instance)
            {
                if (instance == null || m_Wrapper.m_Win10ActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_Win10ActionsCallbackInterfaces.Add(instance);
                @Move_Player.started += instance.OnMove_Player;
                @Move_Player.performed += instance.OnMove_Player;
                @Move_Player.canceled += instance.OnMove_Player;
                @Attack_Player.started += instance.OnAttack_Player;
                @Attack_Player.performed += instance.OnAttack_Player;
                @Attack_Player.canceled += instance.OnAttack_Player;
                @SwitchHotBar_Player.started += instance.OnSwitchHotBar_Player;
                @SwitchHotBar_Player.performed += instance.OnSwitchHotBar_Player;
                @SwitchHotBar_Player.canceled += instance.OnSwitchHotBar_Player;
                @F.started += instance.OnF;
                @F.performed += instance.OnF;
                @F.canceled += instance.OnF;
                @B.started += instance.OnB;
                @B.performed += instance.OnB;
                @B.canceled += instance.OnB;
                @CtrlMouse.started += instance.OnCtrlMouse;
                @CtrlMouse.performed += instance.OnCtrlMouse;
                @CtrlMouse.canceled += instance.OnCtrlMouse;
                @ESC.started += instance.OnESC;
                @ESC.performed += instance.OnESC;
                @ESC.canceled += instance.OnESC;
                @Shift.started += instance.OnShift;
                @Shift.performed += instance.OnShift;
                @Shift.canceled += instance.OnShift;
                @Ctrl.started += instance.OnCtrl;
                @Ctrl.performed += instance.OnCtrl;
                @Ctrl.canceled += instance.OnCtrl;
                @MouseScroll.started += instance.OnMouseScroll;
                @MouseScroll.performed += instance.OnMouseScroll;
                @MouseScroll.canceled += instance.OnMouseScroll;
                @Mouse.started += instance.OnMouse;
                @Mouse.performed += instance.OnMouse;
                @Mouse.canceled += instance.OnMouse;
                @E.started += instance.OnE;
                @E.performed += instance.OnE;
                @E.canceled += instance.OnE;
                @RightClick.started += instance.OnRightClick;
                @RightClick.performed += instance.OnRightClick;
                @RightClick.canceled += instance.OnRightClick;
                @LeftClick.started += instance.OnLeftClick;
                @LeftClick.performed += instance.OnLeftClick;
                @LeftClick.canceled += instance.OnLeftClick;
                @OpenEquipmentPack.started += instance.OnOpenEquipmentPack;
                @OpenEquipmentPack.performed += instance.OnOpenEquipmentPack;
                @OpenEquipmentPack.canceled += instance.OnOpenEquipmentPack;
                @OpenWorkBench.started += instance.OnOpenWorkBench;
                @OpenWorkBench.performed += instance.OnOpenWorkBench;
                @OpenWorkBench.canceled += instance.OnOpenWorkBench;
                @Tab.started += instance.OnTab;
                @Tab.performed += instance.OnTab;
                @Tab.canceled += instance.OnTab;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="Win10Actions" />
            private void UnregisterCallbacks(IWin10Actions instance)
            {
                @Move_Player.started -= instance.OnMove_Player;
                @Move_Player.performed -= instance.OnMove_Player;
                @Move_Player.canceled -= instance.OnMove_Player;
                @Attack_Player.started -= instance.OnAttack_Player;
                @Attack_Player.performed -= instance.OnAttack_Player;
                @Attack_Player.canceled -= instance.OnAttack_Player;
                @SwitchHotBar_Player.started -= instance.OnSwitchHotBar_Player;
                @SwitchHotBar_Player.performed -= instance.OnSwitchHotBar_Player;
                @SwitchHotBar_Player.canceled -= instance.OnSwitchHotBar_Player;
                @F.started -= instance.OnF;
                @F.performed -= instance.OnF;
                @F.canceled -= instance.OnF;
                @B.started -= instance.OnB;
                @B.performed -= instance.OnB;
                @B.canceled -= instance.OnB;
                @CtrlMouse.started -= instance.OnCtrlMouse;
                @CtrlMouse.performed -= instance.OnCtrlMouse;
                @CtrlMouse.canceled -= instance.OnCtrlMouse;
                @ESC.started -= instance.OnESC;
                @ESC.performed -= instance.OnESC;
                @ESC.canceled -= instance.OnESC;
                @Shift.started -= instance.OnShift;
                @Shift.performed -= instance.OnShift;
                @Shift.canceled -= instance.OnShift;
                @Ctrl.started -= instance.OnCtrl;
                @Ctrl.performed -= instance.OnCtrl;
                @Ctrl.canceled -= instance.OnCtrl;
                @MouseScroll.started -= instance.OnMouseScroll;
                @MouseScroll.performed -= instance.OnMouseScroll;
                @MouseScroll.canceled -= instance.OnMouseScroll;
                @Mouse.started -= instance.OnMouse;
                @Mouse.performed -= instance.OnMouse;
                @Mouse.canceled -= instance.OnMouse;
                @E.started -= instance.OnE;
                @E.performed -= instance.OnE;
                @E.canceled -= instance.OnE;
                @RightClick.started -= instance.OnRightClick;
                @RightClick.performed -= instance.OnRightClick;
                @RightClick.canceled -= instance.OnRightClick;
                @LeftClick.started -= instance.OnLeftClick;
                @LeftClick.performed -= instance.OnLeftClick;
                @LeftClick.canceled -= instance.OnLeftClick;
                @OpenEquipmentPack.started -= instance.OnOpenEquipmentPack;
                @OpenEquipmentPack.performed -= instance.OnOpenEquipmentPack;
                @OpenEquipmentPack.canceled -= instance.OnOpenEquipmentPack;
                @OpenWorkBench.started -= instance.OnOpenWorkBench;
                @OpenWorkBench.performed -= instance.OnOpenWorkBench;
                @OpenWorkBench.canceled -= instance.OnOpenWorkBench;
                @Tab.started -= instance.OnTab;
                @Tab.performed -= instance.OnTab;
                @Tab.canceled -= instance.OnTab;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="Win10Actions.UnregisterCallbacks(IWin10Actions)" />.
            /// </summary>
            /// <seealso cref="Win10Actions.UnregisterCallbacks(IWin10Actions)" />
            public void RemoveCallbacks(IWin10Actions instance)
            {
                if (m_Wrapper.m_Win10ActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="Win10Actions.AddCallbacks(IWin10Actions)" />
            /// <seealso cref="Win10Actions.RemoveCallbacks(IWin10Actions)" />
            /// <seealso cref="Win10Actions.UnregisterCallbacks(IWin10Actions)" />
            public void SetCallbacks(IWin10Actions instance)
            {
                foreach (var item in m_Wrapper.m_Win10ActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_Win10ActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="Win10Actions" /> instance referencing this action map.
        /// </summary>
        public Win10Actions @Win10 => new Win10Actions(this);
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Win10" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="Win10Actions.AddCallbacks(IWin10Actions)" />
        /// <seealso cref="Win10Actions.RemoveCallbacks(IWin10Actions)" />
        public interface IWin10Actions
        {
            /// <summary>
            /// Method invoked when associated input action "Move_Player" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnMove_Player(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Attack_Player" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnAttack_Player(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "SwitchHotBar_Player" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSwitchHotBar_Player(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "F" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnF(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "B" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnB(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "CtrlMouse" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnCtrlMouse(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "ESC" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnESC(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Shift" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnShift(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Ctrl" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnCtrl(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "MouseScroll" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnMouseScroll(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Mouse" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnMouse(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "E" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnE(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "RightClick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnRightClick(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "LeftClick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnLeftClick(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "OpenEquipmentPack" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnOpenEquipmentPack(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "OpenWorkBench" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnOpenWorkBench(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Tab" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnTab(InputAction.CallbackContext context);
        }
    }
}
